---
openapi: 3.1.0
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  "/api/v1/prices":
    get:
      tags:
        - price-controller
      operationId: getApplicablePrice
      parameters:
        - name: application_date
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: product_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: brand_id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            "*/*":
              schema:
                "$ref": "#/components/schemas/PriceResponse"
components:
  schemas:
    PriceResponse:
      type: object
      properties:
        productId:
          type: integer
          format: int64
        brandId:
          type: integer
          format: int64
        priceListId:
          type: integer
          format: int64
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        finalPrice:
          type: number
          format: double
